import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScrolling";

const inter = Inter({ subsets: ["latin"] });
const monsterrat = Montserrat({
  subsets: ["cyrillic", "latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hide-scroll">
      <body className={monsterrat.className + " bg-black text-white"}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
